package model.persistance;

// Generated 29 juin 2010 01:06:24 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Abuse generated by hbm2java
 */
public class Abuse implements java.io.Serializable {

	private Integer idAbuse;
	private String abuseType;
	private Date dateAbuse;
	private String message;
	private Integer idSender;
	private Integer idGuilty;

	public Abuse() {
	}

	public Abuse(String abuseType, Date dateAbuse, String message,
			Integer idSender, Integer idGuilty) {
		this.abuseType = abuseType;
		this.dateAbuse = dateAbuse;
		this.message = message;
		this.idSender = idSender;
		this.idGuilty = idGuilty;
	}

	public Integer getIdAbuse() {
		return this.idAbuse;
	}

	public void setIdAbuse(Integer idAbuse) {
		this.idAbuse = idAbuse;
	}

	public String getAbuseType() {
		return this.abuseType;
	}

	public void setAbuseType(String abuseType) {
		this.abuseType = abuseType;
	}

	public Date getDateAbuse() {
		return this.dateAbuse;
	}

	public void setDateAbuse(Date dateAbuse) {
		this.dateAbuse = dateAbuse;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public Integer getIdSender() {
		return this.idSender;
	}

	public void setIdSender(Integer idSender) {
		this.idSender = idSender;
	}

	public Integer getIdGuilty() {
		return this.idGuilty;
	}

	public void setIdGuilty(Integer idGuilty) {
		this.idGuilty = idGuilty;
	}

}
