package model.persistance;

// Generated 29 juin 2010 01:06:24 by Hibernate Tools 3.2.4.GA

/**
 * Adress generated by hbm2java
 */
public class Adress implements java.io.Serializable {

	private Integer idAdress;
	private Member member;
	private String street;
	private String town;
	private String zip;
	private String country;

	public Adress() {
	}

	public Adress(Member member) {
		this.member = member;
	}

	public Adress(Member member, String street, String town, String zip,
			String country) {
		this.member = member;
		this.street = street;
		this.town = town;
		this.zip = zip;
		this.country = country;
	}

	public Integer getIdAdress() {
		return this.idAdress;
	}

	public void setIdAdress(Integer idAdress) {
		this.idAdress = idAdress;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getTown() {
		return this.town;
	}

	public void setTown(String town) {
		this.town = town;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

}
