package model.persistance;

// Generated 29 juin 2010 01:06:24 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Book generated by hbm2java
 */
public class Book implements java.io.Serializable {

	private Integer idBook;
	private Member member;
	private Category category;
	private String description;
	private String linkBook;
	private Integer nbPages;
	private long nbRead;
	private Double totalRating;
	private boolean isValid;
	private Date publishingDate;
	private String linkImage;
	private String title;
	private int nbDownload;
	private double price;
	private boolean isSell;
	private boolean isMine;
	private String author;
	private String uniqCode;
	private String linkImageBig;
	private String proofExplain;
	private String demoPage;
	private boolean deleted;
	private String key_linkImageBig;
	private String key_linkImage;
	private String key_linkBook;
	private String linkBookDemo;
	private Set orderBooks = new HashSet(0);
	private Set members = new HashSet(0);
	private Set themeGroups = new HashSet(0);
	private Set tagBooks = new HashSet(0);
	private Set voteBooks = new HashSet(0);
	private Set messageBooks = new HashSet(0);
	private Set versionBooks = new HashSet(0);
	private Set proofDoc = new HashSet(0);
	
	
	public Book() {
	}

	public Book(Member member, Category category) {
		this.member = member;
		this.category = category;
	}
	public Book(Member member, Category category, String description,

			String linkBook, Integer nbPages, Double totalRating,

			boolean isValid, Date publishingDate, String linkImage,

			String title, Integer nbDownload, double price, boolean isSell,

			boolean isMine, String auteur, String uniqCode,

			String linkImageSmall, String linkImageBig) {

			this.member = member;

			this.category = category;

			this.description = description;

			this.linkBook = linkBook;

			this.nbPages = nbPages;

			this.totalRating = totalRating;

			this.isValid = isValid;

			this.publishingDate = publishingDate;

			this.linkImage = linkImage;

			this.title = title;

			this.nbDownload = nbDownload;

			this.price = price;

			this.isSell = isSell;

			this.isMine = isMine;

			this.author = auteur;

			this.uniqCode = uniqCode;

			this.linkImageBig = linkImageBig;


			}



	public Book(Member member, Category category, String description,
			String linkBook, Integer nbPages, Double totalRating,
			boolean isValid, Date publishingDate, String linkImage,
			String title, Integer nbDownload, double price, boolean isSell,
			boolean isMine, String auteur, String uniqCode,
			String linkImageBig, Set orderBooks, Set members, Set themeGroups,
			Set tagBooks, Set voteBooks, Set messageBooks, Set versionBooks) {
		this.member = member;
		this.category = category;
		this.description = description;
		this.linkBook = linkBook;
		this.nbPages = nbPages;
		this.totalRating = totalRating;
		this.isValid = isValid;
		this.publishingDate = publishingDate;
		this.linkImage = linkImage;
		this.title = title;
		this.nbDownload = nbDownload;
		this.price = price;
		this.isSell = isSell;
		this.isMine = isMine;
		this.author = auteur;
		this.uniqCode = uniqCode;
		this.linkImageBig = linkImageBig;
		this.orderBooks = orderBooks;
		this.members = members;
		this.themeGroups = themeGroups;
		this.tagBooks = tagBooks;
		this.voteBooks = voteBooks;
		this.messageBooks = messageBooks;
		this.versionBooks = versionBooks;
	}

	public Integer getIdBook() {
		return this.idBook;
	}

	public void setIdBook(Integer idBook) {
		this.idBook = idBook;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLinkBook() {
		return this.linkBook;
	}

	public void setLinkBook(String linkBook) {
		this.linkBook = linkBook;
	}

	public Integer getNbPages() {
		return this.nbPages;
	}

	public void setNbPages(Integer nbPages) {
		this.nbPages = nbPages;
	}

	
	public long getNbRead() {
		return nbRead;
	}

	public void setNbRead(long nbRead) {
		this.nbRead = nbRead;
	}

	public Double getTotalRating() {
		return this.totalRating;
	}

	public void setTotalRating(Double totalRating) {
		this.totalRating = totalRating;
	}

	public boolean getIsValid() {
		return this.isValid;
	}

	public void setIsValid(boolean isValid) {
		this.isValid = isValid;
	}

	public Date getPublishingDate() {
		return this.publishingDate;
	}

	public void setPublishingDate(Date publishingDate) {
		this.publishingDate = publishingDate;
	}

	public String getLinkImage() {
		return this.linkImage;
	}

	public void setLinkImage(String linkImage) {
		this.linkImage = linkImage;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public int getNbDownload() {
		return this.nbDownload;
	}

	public void setNbDownload(int nbDownload) {
		this.nbDownload = nbDownload;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public boolean getIsSell() {
		return this.isSell;
	}

	public void setIsSell(boolean isSell) {
		this.isSell = isSell;
	}

	public boolean getIsMine() {
		return this.isMine;
	}

	public void setIsMine(boolean isMine) {
		this.isMine = isMine;
	}



	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getUniqCode() {
		return this.uniqCode;
	}

	public void setUniqCode(String uniqCode) {
		this.uniqCode = uniqCode;
	}

	public String getLinkImageBig() {
		return this.linkImageBig;
	}

	public void setLinkImageBig(String linkImageBig) {
		this.linkImageBig = linkImageBig;
	}

	public boolean isDeleted() {
		return deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	
	public String getKey_linkImageBig() {
		return key_linkImageBig;
	}

	public void setKey_linkImageBig(String keyLinkImageBig) {
		key_linkImageBig = keyLinkImageBig;
	}

	public String getKey_linkImage() {
		return key_linkImage;
	}

	public void setKey_linkImage(String keyLinkImage) {
		key_linkImage = keyLinkImage;
	}

	public String getKey_linkBook() {
		return key_linkBook;
	}

	public void setKey_linkBook(String keyLinkBook) {
		key_linkBook = keyLinkBook;
	}



	
	

	public String getProofExplain() {
		return proofExplain;
	}

	public void setProofExplain(String proofExplain) {
		this.proofExplain = proofExplain;
	}

	public String getDemoPage() {
		return demoPage;
	}

	public void setDemoPage(String demoPage) {
		this.demoPage = demoPage;
	}

	
	
	public String getLinkBookDemo() {
		return linkBookDemo;
	}

	public void setLinkBookDemo(String linkBookDemo) {
		this.linkBookDemo = linkBookDemo;
	}

	public Set getOrderBooks() {
		return orderBooks;
	}

	public void setOrderBooks(Set orderBooks) {
		this.orderBooks = orderBooks;
	}

	public Set getMembers() {
		return this.members;
	}

	public void setMembers(Set members) {
		this.members = members;
	}

	public Set getThemeGroups() {
		return this.themeGroups;
	}

	public void setThemeGroups(Set themeGroups) {
		this.themeGroups = themeGroups;
	}

	public Set getTagBooks() {
		return this.tagBooks;
	}

	public void setTagBooks(Set tagBooks) {
		this.tagBooks = tagBooks;
	}

	public Set getVoteBooks() {
		return this.voteBooks;
	}

	public void setVoteBooks(Set voteBooks) {
		this.voteBooks = voteBooks;
	}

	public Set getMessageBooks() {
		return this.messageBooks;
	}

	public void setMessageBooks(Set messageBooks) {
		this.messageBooks = messageBooks;
	}

	public Set getVersionBooks() {
		return this.versionBooks;
	}

	public void setVersionBooks(Set versionBooks) {
		this.versionBooks = versionBooks;
	}

	public Set getProofDoc() {
		return proofDoc;
	}

	public void setProofDoc(Set proofDoc) {
		this.proofDoc = proofDoc;
	}
	

}
