package model.persistance;

// Generated 29 juin 2010 01:06:24 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * ClassMember generated by hbm2java
 */
public class ClassMember implements java.io.Serializable {

	private Integer idClass;
	private String name;
	private String description;
	private Boolean isPay;
	private Set jobs = new HashSet(0);
	private Set levelMembers = new HashSet(0);

	public ClassMember() {
	}

	public ClassMember(String name, String description, Boolean isPay,
			Set jobs, Set levelMembers) {
		this.name = name;
		this.description = description;
		this.isPay = isPay;
		this.jobs = jobs;
		this.levelMembers = levelMembers;
	}

	public Integer getIdClass() {
		return this.idClass;
	}

	public void setIdClass(Integer idClass) {
		this.idClass = idClass;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getIsPay() {
		return this.isPay;
	}

	public void setIsPay(Boolean isPay) {
		this.isPay = isPay;
	}

	public Set getJobs() {
		return this.jobs;
	}

	public void setJobs(Set jobs) {
		this.jobs = jobs;
	}

	public Set getLevelMembers() {
		return this.levelMembers;
	}

	public void setLevelMembers(Set levelMembers) {
		this.levelMembers = levelMembers;
	}

}
