package model.persistance;

// Generated 29 juin 2010 01:06:24 by Hibernate Tools 3.2.4.GA

/**
 * FavouriteAuthor generated by hbm2java
 */
public class FavouriteAuthor implements java.io.Serializable {

	private Integer idAuthor;
	private Member member;
	private String authorName;
	private String link;

	public FavouriteAuthor() {
	}

	public FavouriteAuthor(Member member) {
		this.member = member;
	}

	public FavouriteAuthor(Member member, String authorName, String link) {
		this.member = member;
		this.authorName = authorName;
		this.link = link;
	}

	public Integer getIdAuthor() {
		return this.idAuthor;
	}

	public void setIdAuthor(Integer idAuthor) {
		this.idAuthor = idAuthor;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public String getAuthorName() {
		return this.authorName;
	}

	public void setAuthorName(String authorName) {
		this.authorName = authorName;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

}
