package model.persistance;

// Generated 29 juin 2010 01:06:24 by Hibernate Tools 3.2.4.GA

/**
 * FavouriteBook generated by hbm2java
 */
public class FavouriteBook implements java.io.Serializable {

	private Integer idLivre;
	private Member member;
	private String bookName;
	private String link;

	public FavouriteBook() {
	}

	public FavouriteBook(Member member) {
		this.member = member;
	}

	public FavouriteBook(Member member, String bookName, String link) {
		this.member = member;
		this.bookName = bookName;
		this.link = link;
	}

	public Integer getIdLivre() {
		return this.idLivre;
	}

	public void setIdLivre(Integer idLivre) {
		this.idLivre = idLivre;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public String getBookName() {
		return this.bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

}
