package model.persistance;

// Generated 29 juin 2010 01:06:24 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * FolderEmail generated by hbm2java
 */
public class FolderEmail implements java.io.Serializable {

	private Integer idFolder;
	private String subject;
	private Set messageEmails = new HashSet(0);

	public FolderEmail() {
	}

	public FolderEmail(String subject, Set messageEmails) {
		this.subject = subject;
		this.messageEmails = messageEmails;
	}

	public Integer getIdFolder() {
		return this.idFolder;
	}

	public void setIdFolder(Integer idFolder) {
		this.idFolder = idFolder;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public Set getMessageEmails() {
		return this.messageEmails;
	}

	public void setMessageEmails(Set messageEmails) {
		this.messageEmails = messageEmails;
	}

}
