package model.persistance;

// Generated 29 juin 2010 01:06:24 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Level generated by hbm2java
 */
public class Level implements java.io.Serializable {

	private Integer idLevel;
	private Integer numbr;
	private String description;
	private Integer expMin;
	private Integer expMax;
	private Set jobs = new HashSet(0);
	private Set levelMembers = new HashSet(0);

	public Level() {
	}

	public Level(Integer numbr, String description, Integer expMin,
			Integer expMax, Set jobs, Set levelMembers) {
		this.numbr = numbr;
		this.description = description;
		this.expMin = expMin;
		this.expMax = expMax;
		this.jobs = jobs;
		this.levelMembers = levelMembers;
	}

	public Integer getIdLevel() {
		return this.idLevel;
	}

	public void setIdLevel(Integer idLevel) {
		this.idLevel = idLevel;
	}

	public Integer getNumbr() {
		return this.numbr;
	}

	public void setNumbr(Integer numbr) {
		this.numbr = numbr;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getExpMin() {
		return this.expMin;
	}

	public void setExpMin(Integer expMin) {
		this.expMin = expMin;
	}

	public Integer getExpMax() {
		return this.expMax;
	}

	public void setExpMax(Integer expMax) {
		this.expMax = expMax;
	}

	public Set getJobs() {
		return this.jobs;
	}

	public void setJobs(Set jobs) {
		this.jobs = jobs;
	}

	public Set getLevelMembers() {
		return this.levelMembers;
	}

	public void setLevelMembers(Set levelMembers) {
		this.levelMembers = levelMembers;
	}

}
