package model.persistance;

// Generated 29 juin 2010 01:06:24 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Member generated by hbm2java
 */
public class Member implements java.io.Serializable {

	private Integer idMember;
	private String name;
	private String lastName;
	private String login;
	private String password;
	private String description;
	private Date registrationDate;
	private String avatarUrl;
	private Character gender;
	private Date birth;
	private String email;
	private Double rating;
	private String secretQuestion;
	private String responseQuestion;
	private String avatarUrlBig;
	private String loginReferer;
	private boolean deleted;
	private String key_avatarUrlBig;
	private String key_avatarUrl;
	private Set themeGroups = new HashSet(0);
	private Set books = new HashSet(0);
	private Set messageRequests = new HashSet(0);
	private Set messageBooks = new HashSet(0);
	private Set themeGroups_1 = new HashSet(0);
	private Set voteMembers = new HashSet(0);
	private Set messageGroups = new HashSet(0);
	private Set requests = new HashSet(0);
	private Set books_1 = new HashSet(0);
	private Set responseMessageGroups = new HashSet(0);
	private Set messageEmailsForIdMemberSender = new HashSet(0);
	private Set messageEmailsForIdMember = new HashSet(0);
	private Set orderCustomers = new HashSet(0);
	private Set levelMembers = new HashSet(0);
	private Set membersForIdMember = new HashSet(0);
	private Set membersForIdMemberFriend = new HashSet(0);
	private Set messageMembersForIdMember = new HashSet(0);
	private Set messageMembersForIdMemberSender = new HashSet(0);
	private Set membersForIdMember_1 = new HashSet(0);
	private Set membersForIdMemberFollow = new HashSet(0);
	private Set favouriteBooks = new HashSet(0);
	private Set requestFriendsForIdMemberRecipient = new HashSet(0);
	private Set requestFriendsForIdMember = new HashSet(0);
	private Set adresses = new HashSet(0);
	private Set responseMessageMembers = new HashSet(0);
	private Set favouriteAuthors = new HashSet(0);
	private Set responseMessageBooks = new HashSet(0);

	public Member() {
	}

	public Member(String name, String lastName, String login, String password,
			String description, Date registrationDate, String avatarUrl,
			Character gender, Date birth, String email, Double rating){
			this.name = name;
			this.lastName = lastName;
			this.login = login;
			this.password = password;
			this.description = description;
			this.registrationDate = registrationDate;
			this.avatarUrl = avatarUrl;
			this.gender = gender;
			this.birth = birth;
			this.email = email;
			this.rating = rating;
			}
			 
	public Member(String name, String lastName, String login, String password,
			String description, Date registrationDate, String avatarUrl,
			Character gender, Date birth, String email, Double rating,
			String secretQuestion, String responseQuestion,
			String avatarUrlBig, String loginReferer, Set themeGroups,
			Set books, Set messageRequests, Set messageBooks,
			Set themeGroups_1, Set voteMembers, Set messageGroups,
			Set requests, Set books_1, Set responseMessageGroups,
			Set messageEmailsForIdMemberSender, Set messageEmailsForIdMember,
			Set orderCustomers, Set levelMembers, Set membersForIdMember,
			Set membersForIdMemberFriend, Set messageMembersForIdMember,
			Set messageMembersForIdMemberSender, Set membersForIdMember_1,
			Set membersForIdMemberFollow, Set favouriteBooks,
			Set requestFriendsForIdMemberRecipient,
			Set requestFriendsForIdMember, Set adresses,
			Set responseMessageMembers, Set favouriteAuthors,
			Set responseMessageBooks) {
		this.name = name;
		this.lastName = lastName;
		this.login = login;
		this.password = password;
		this.description = description;
		this.registrationDate = registrationDate;
		this.avatarUrl = avatarUrl;
		this.gender = gender;
		this.birth = birth;
		this.email = email;
		this.rating = rating;
		this.secretQuestion = secretQuestion;
		this.responseQuestion = responseQuestion;
		this.avatarUrlBig = avatarUrlBig;
		this.loginReferer = loginReferer;
		this.themeGroups = themeGroups;
		this.books = books;
		this.messageRequests = messageRequests;
		this.messageBooks = messageBooks;
		this.themeGroups_1 = themeGroups_1;
		this.voteMembers = voteMembers;
		this.messageGroups = messageGroups;
		this.requests = requests;
		this.books_1 = books_1;
		this.responseMessageGroups = responseMessageGroups;
		this.messageEmailsForIdMemberSender = messageEmailsForIdMemberSender;
		this.messageEmailsForIdMember = messageEmailsForIdMember;
		this.orderCustomers = orderCustomers;
		this.levelMembers = levelMembers;
		this.membersForIdMember = membersForIdMember;
		this.membersForIdMemberFriend = membersForIdMemberFriend;
		this.messageMembersForIdMember = messageMembersForIdMember;
		this.messageMembersForIdMemberSender = messageMembersForIdMemberSender;
		this.membersForIdMember_1 = membersForIdMember_1;
		this.membersForIdMemberFollow = membersForIdMemberFollow;
		this.favouriteBooks = favouriteBooks;
		this.requestFriendsForIdMemberRecipient = requestFriendsForIdMemberRecipient;
		this.requestFriendsForIdMember = requestFriendsForIdMember;
		this.adresses = adresses;
		this.responseMessageMembers = responseMessageMembers;
		this.favouriteAuthors = favouriteAuthors;
		this.responseMessageBooks = responseMessageBooks;
	}

	public Integer getIdMember() {
		return this.idMember;
	}

	public void setIdMember(Integer idMember) {
		this.idMember = idMember;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}

	public String getAvatarUrl() {
		return this.avatarUrl;
	}

	public void setAvatarUrl(String avatarUrl) {
		this.avatarUrl = avatarUrl;
	}

	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	public Date getBirth() {
		return this.birth;
	}

	public void setBirth(Date birth) {
		this.birth = birth;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Double getRating() {
		return this.rating;
	}

	public void setRating(Double rating) {
		this.rating = rating;
	}

	public String getSecretQuestion() {
		return this.secretQuestion;
	}

	public void setSecretQuestion(String secretQuestion) {
		this.secretQuestion = secretQuestion;
	}

	public String getResponseQuestion() {
		return this.responseQuestion;
	}

	public void setResponseQuestion(String responseQuestion) {
		this.responseQuestion = responseQuestion;
	}

	public String getAvatarUrlBig() {
		return this.avatarUrlBig;
	}

	public void setAvatarUrlBig(String avatarUrlBig) {
		this.avatarUrlBig = avatarUrlBig;
	}

	public String getLoginReferer() {
		return this.loginReferer;
	}

	public void setLoginReferer(String loginReferer) {
		this.loginReferer = loginReferer;
	}
	
	public boolean isDeleted() {
		return deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}
	
	
	public String getKey_avatarUrlBig() {
		return key_avatarUrlBig;
	}

	public void setKey_avatarUrlBig(String keyAvatarUrlBig) {
		key_avatarUrlBig = keyAvatarUrlBig;
	}

	public String getKey_avatarUrl() {
		return key_avatarUrl;
	}

	public void setKey_avatarUrl(String keyAvatarUrl) {
		key_avatarUrl = keyAvatarUrl;
	}

	public Set getThemeGroups() {
		return this.themeGroups;
	}

	public void setThemeGroups(Set themeGroups) {
		this.themeGroups = themeGroups;
	}

	public Set getBooks() {
		return this.books;
	}

	public void setBooks(Set books) {
		this.books = books;
	}

	public Set getMessageRequests() {
		return this.messageRequests;
	}

	public void setMessageRequests(Set messageRequests) {
		this.messageRequests = messageRequests;
	}

	public Set getMessageBooks() {
		return this.messageBooks;
	}

	public void setMessageBooks(Set messageBooks) {
		this.messageBooks = messageBooks;
	}

	public Set getThemeGroups_1() {
		return this.themeGroups_1;
	}

	public void setThemeGroups_1(Set themeGroups_1) {
		this.themeGroups_1 = themeGroups_1;
	}

	public Set getVoteMembers() {
		return this.voteMembers;
	}

	public void setVoteMembers(Set voteMembers) {
		this.voteMembers = voteMembers;
	}

	public Set getMessageGroups() {
		return this.messageGroups;
	}

	public void setMessageGroups(Set messageGroups) {
		this.messageGroups = messageGroups;
	}

	public Set getRequests() {
		return this.requests;
	}

	public void setRequests(Set requests) {
		this.requests = requests;
	}

	public Set getBooks_1() {
		return this.books_1;
	}

	public void setBooks_1(Set books_1) {
		this.books_1 = books_1;
	}

	public Set getResponseMessageGroups() {
		return this.responseMessageGroups;
	}

	public void setResponseMessageGroups(Set responseMessageGroups) {
		this.responseMessageGroups = responseMessageGroups;
	}

	public Set getMessageEmailsForIdMemberSender() {
		return this.messageEmailsForIdMemberSender;
	}

	public void setMessageEmailsForIdMemberSender(
			Set messageEmailsForIdMemberSender) {
		this.messageEmailsForIdMemberSender = messageEmailsForIdMemberSender;
	}

	public Set getMessageEmailsForIdMember() {
		return this.messageEmailsForIdMember;
	}

	public void setMessageEmailsForIdMember(Set messageEmailsForIdMember) {
		this.messageEmailsForIdMember = messageEmailsForIdMember;
	}

	public Set getOrderCustomers() {
		return this.orderCustomers;
	}

	public void setOrderCustomers(Set orderCustomers) {
		this.orderCustomers = orderCustomers;
	}

	public Set getLevelMembers() {
		return this.levelMembers;
	}

	public void setLevelMembers(Set levelMembers) {
		this.levelMembers = levelMembers;
	}

	public Set getMembersForIdMember() {
		return this.membersForIdMember;
	}

	public void setMembersForIdMember(Set membersForIdMember) {
		this.membersForIdMember = membersForIdMember;
	}

	public Set getMembersForIdMemberFriend() {
		return this.membersForIdMemberFriend;
	}

	public void setMembersForIdMemberFriend(Set membersForIdMemberFriend) {
		this.membersForIdMemberFriend = membersForIdMemberFriend;
	}

	public Set getMessageMembersForIdMember() {
		return this.messageMembersForIdMember;
	}

	public void setMessageMembersForIdMember(Set messageMembersForIdMember) {
		this.messageMembersForIdMember = messageMembersForIdMember;
	}

	public Set getMessageMembersForIdMemberSender() {
		return this.messageMembersForIdMemberSender;
	}

	public void setMessageMembersForIdMemberSender(
			Set messageMembersForIdMemberSender) {
		this.messageMembersForIdMemberSender = messageMembersForIdMemberSender;
	}

	public Set getMembersForIdMember_1() {
		return this.membersForIdMember_1;
	}

	public void setMembersForIdMember_1(Set membersForIdMember_1) {
		this.membersForIdMember_1 = membersForIdMember_1;
	}

	public Set getMembersForIdMemberFollow() {
		return this.membersForIdMemberFollow;
	}

	public void setMembersForIdMemberFollow(Set membersForIdMemberFollow) {
		this.membersForIdMemberFollow = membersForIdMemberFollow;
	}

	public Set getFavouriteBooks() {
		return this.favouriteBooks;
	}

	public void setFavouriteBooks(Set favouriteBooks) {
		this.favouriteBooks = favouriteBooks;
	}

	public Set getRequestFriendsForIdMemberRecipient() {
		return this.requestFriendsForIdMemberRecipient;
	}

	public void setRequestFriendsForIdMemberRecipient(
			Set requestFriendsForIdMemberRecipient) {
		this.requestFriendsForIdMemberRecipient = requestFriendsForIdMemberRecipient;
	}

	public Set getRequestFriendsForIdMember() {
		return this.requestFriendsForIdMember;
	}

	public void setRequestFriendsForIdMember(Set requestFriendsForIdMember) {
		this.requestFriendsForIdMember = requestFriendsForIdMember;
	}

	public Set getAdresses() {
		return this.adresses;
	}

	public void setAdresses(Set adresses) {
		this.adresses = adresses;
	}

	public Set getResponseMessageMembers() {
		return this.responseMessageMembers;
	}

	public void setResponseMessageMembers(Set responseMessageMembers) {
		this.responseMessageMembers = responseMessageMembers;
	}

	public Set getFavouriteAuthors() {
		return this.favouriteAuthors;
	}

	public void setFavouriteAuthors(Set favouriteAuthors) {
		this.favouriteAuthors = favouriteAuthors;
	}

	public Set getResponseMessageBooks() {
		return this.responseMessageBooks;
	}

	public void setResponseMessageBooks(Set responseMessageBooks) {
		this.responseMessageBooks = responseMessageBooks;
	}

}
