package model.persistance;

// Generated 29 juin 2010 01:06:24 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * MessageRequest generated by hbm2java
 */
public class MessageRequest implements java.io.Serializable {

	private Integer idMessage;
	private Request request;
	private Member member;
	private Date publishDate;
	private String body;

	public MessageRequest() {
	}

	public MessageRequest(Request request, Member member) {
		this.request = request;
		this.member = member;
	}

	public MessageRequest(Request request, Member member, Date publishDate,
			String body) {
		this.request = request;
		this.member = member;
		this.publishDate = publishDate;
		this.body = body;
	}

	public Integer getIdMessage() {
		return this.idMessage;
	}

	public void setIdMessage(Integer idMessage) {
		this.idMessage = idMessage;
	}

	public Request getRequest() {
		return this.request;
	}

	public void setRequest(Request request) {
		this.request = request;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public Date getPublishDate() {
		return this.publishDate;
	}

	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

}
