package model.persistance;

// Generated 29 juin 2010 01:06:24 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MessageBook generated by hbm2java
 */
public class MessageBook implements java.io.Serializable {

	private Integer idMessage;
	private Book book;
	private Member member;
	private Date publishDate;
	private String body;
	private boolean deleted;
	private Set responseMessageBooks = new HashSet(0);

	public MessageBook() {
	}

	public MessageBook(Book book, Member member) {
		this.book = book;
		this.member = member;
	}

	public MessageBook(Book book, Member member, Date publishDate, String body,
			Set responseMessageBooks) {
		this.book = book;
		this.member = member;
		this.publishDate = publishDate;
		this.body = body;
		this.responseMessageBooks = responseMessageBooks;
	}

	public Integer getIdMessage() {
		return this.idMessage;
	}

	public void setIdMessage(Integer idMessage) {
		this.idMessage = idMessage;
	}

	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public Date getPublishDate() {
		return this.publishDate;
	}

	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	public boolean isDeleted() {
		return deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}
	
	public Set getResponseMessageBooks() {
		return this.responseMessageBooks;
	}

	public void setResponseMessageBooks(Set responseMessageBooks) {
		this.responseMessageBooks = responseMessageBooks;
	}

}
