package model.persistance;

// Generated 29 juin 2010 01:06:24 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MessageGroup generated by hbm2java
 */
public class MessageGroup implements java.io.Serializable {

	private Integer idMessage;
	private ThemeGroup themeGroup;
	private Member member;
	private Date publishDate;
	private String body;
	private boolean deleted;
	private Set responseMessageGroups = new HashSet(0);

	public MessageGroup() {
	}

	public MessageGroup(ThemeGroup themeGroup, Member member) {
		this.themeGroup = themeGroup;
		this.member = member;
	}

	public MessageGroup(ThemeGroup themeGroup, Member member, Date publishDate,
			String body, Set responseMessageGroups) {
		this.themeGroup = themeGroup;
		this.member = member;
		this.publishDate = publishDate;
		this.body = body;
		this.responseMessageGroups = responseMessageGroups;
	}

	public Integer getIdMessage() {
		return this.idMessage;
	}

	public void setIdMessage(Integer idMessage) {
		this.idMessage = idMessage;
	}

	public ThemeGroup getThemeGroup() {
		return this.themeGroup;
	}

	public void setThemeGroup(ThemeGroup themeGroup) {
		this.themeGroup = themeGroup;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public Date getPublishDate() {
		return this.publishDate;
	}

	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	public boolean isDeleted() {
		return deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}
	
	public Set getResponseMessageGroups() {
		return this.responseMessageGroups;
	}

	public void setResponseMessageGroups(Set responseMessageGroups) {
		this.responseMessageGroups = responseMessageGroups;
	}

}
