package model.persistance;

// Generated 29 juin 2010 01:06:24 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrderCustomer generated by hbm2java
 */
public class OrderCustomer implements java.io.Serializable {

	public static final String CB="c";
	public static final double TVA=19.6;
	private Integer idOrderCustomer;
	private Member member;
	private Date dateOrder;
	private String paymentType;
	private Double price;
	private String refOrder;
	private boolean isTreated;
	
	//pdf for invoice
	private String linkFileOrder;
	private String description;
	private Double tva;
	private Set orderBooks = new HashSet(0);

	public OrderCustomer() {
	}

	public OrderCustomer(Member member) {
		this.member = member;
	}

	public OrderCustomer(Member member, Date dateOrder, String paymentType,
			Double price, String refOrder, boolean isTreated,
			String linkFileOrder, String description, Double tva) {
		this.member = member;
		this.dateOrder = dateOrder;
		this.paymentType = paymentType;
		this.price = price;
		this.refOrder = refOrder;
		this.isTreated = isTreated;
		this.linkFileOrder = linkFileOrder;
		this.description = description;
		this.tva = tva;
	
	}
	
	public OrderCustomer(Member member, Date dateOrder, String paymentType,
			Double price, String refOrder, boolean isTreated,
			String linkFileOrder, String description, Double tva, Set orderBooks) {
		this.member = member;
		this.dateOrder = dateOrder;
		this.paymentType = paymentType;
		this.price = price;
		this.refOrder = refOrder;
		this.isTreated = isTreated;
		this.linkFileOrder = linkFileOrder;
		this.description = description;
		this.tva = tva;
		this.orderBooks = orderBooks;
	}
	
	

	public Integer getIdOrderCustomer() {
		return this.idOrderCustomer;
	}

	public void setIdOrderCustomer(Integer idOrderCustomer) {
		this.idOrderCustomer = idOrderCustomer;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public Date getDateOrder() {
		return this.dateOrder;
	}

	public void setDateOrder(Date dateOrder) {
		this.dateOrder = dateOrder;
	}

	public String getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public String getRefOrder() {
		return this.refOrder;
	}

	public void setRefOrder(String refOrder) {
		this.refOrder = refOrder;
	}

	public boolean getIsTreated() {
		return this.isTreated;
	}

	public void setIsTreated(boolean isTreated) {
		this.isTreated = isTreated;
	}

	public String getLinkFileOrder() {
		return this.linkFileOrder;
	}

	public void setLinkFileOrder(String linkFileOrder) {
		this.linkFileOrder = linkFileOrder;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Double getTva() {
		return this.tva;
	}

	public void setTva(Double tva) {
		this.tva = tva;
	}

	public Set getOrderBooks() {
		return this.orderBooks;
	}

	public void setOrderBooks(Set orderBooks) {
		this.orderBooks = orderBooks;
	}

}
