package model.persistance;

// Generated 29 juin 2010 01:06:24 by Hibernate Tools 3.2.4.GA

/**
 * RequestFriend generated by hbm2java
 */
public class RequestFriend implements java.io.Serializable {

	private Integer idRequestFriend;
	private Member memberByIdMemberRecipient;
	private Member memberByIdMember;
	private Boolean treated;
	private String uniqCode;
	private Boolean isRead;
	private Boolean isOk;

	public RequestFriend() {
	}

	public RequestFriend(Member memberByIdMemberRecipient,
			Member memberByIdMember) {
		this.memberByIdMemberRecipient = memberByIdMemberRecipient;
		this.memberByIdMember = memberByIdMember;
	}

	public RequestFriend(Member memberByIdMemberRecipient,
			Member memberByIdMember, Boolean treated, String uniqCode,
			Boolean isRead, Boolean isOk) {
		this.memberByIdMemberRecipient = memberByIdMemberRecipient;
		this.memberByIdMember = memberByIdMember;
		this.treated = treated;
		this.uniqCode = uniqCode;
		this.isRead = isRead;
		this.isOk = isOk;
	}

	public Integer getIdRequestFriend() {
		return this.idRequestFriend;
	}

	public void setIdRequestFriend(Integer idRequestFriend) {
		this.idRequestFriend = idRequestFriend;
	}

	public Member getMemberByIdMemberRecipient() {
		return this.memberByIdMemberRecipient;
	}

	public void setMemberByIdMemberRecipient(Member memberByIdMemberRecipient) {
		this.memberByIdMemberRecipient = memberByIdMemberRecipient;
	}

	public Member getMemberByIdMember() {
		return this.memberByIdMember;
	}

	public void setMemberByIdMember(Member memberByIdMember) {
		this.memberByIdMember = memberByIdMember;
	}

	public Boolean getTreated() {
		return this.treated;
	}

	public void setTreated(Boolean treated) {
		this.treated = treated;
	}

	public String getUniqCode() {
		return this.uniqCode;
	}

	public void setUniqCode(String uniqCode) {
		this.uniqCode = uniqCode;
	}

	public Boolean getIsRead() {
		return this.isRead;
	}

	public void setIsRead(Boolean isRead) {
		this.isRead = isRead;
	}

	public Boolean getIsOk() {
		return this.isOk;
	}

	public void setIsOk(Boolean isOk) {
		this.isOk = isOk;
	}

}
