package model.persistance;

// Generated 29 juin 2010 01:06:24 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Request generated by hbm2java
 */
public class Request implements java.io.Serializable {

	private Integer idRequest;
	private ThemeGroup themeGroup;
	private Member member;
	private String title;
	private String description;
	private Double rating;
	private Date publishdate;
	private Set messageRequests = new HashSet(0);
	private Set voteRequests = new HashSet(0);

	public Request() {
	}

	public Request(ThemeGroup themeGroup, Member member) {
		this.themeGroup = themeGroup;
		this.member = member;
	}

	public Request(ThemeGroup themeGroup, Member member, String title,
			String description, Double rating, Date publishdate,
			Set messageRequests, Set voteRequests) {
		this.themeGroup = themeGroup;
		this.member = member;
		this.title = title;
		this.description = description;
		this.rating = rating;
		this.publishdate = publishdate;
		this.messageRequests = messageRequests;
		this.voteRequests = voteRequests;
	}

	public Integer getIdRequest() {
		return this.idRequest;
	}

	public void setIdRequest(Integer idRequest) {
		this.idRequest = idRequest;
	}

	public ThemeGroup getThemeGroup() {
		return this.themeGroup;
	}

	public void setThemeGroup(ThemeGroup themeGroup) {
		this.themeGroup = themeGroup;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Double getRating() {
		return this.rating;
	}

	public void setRating(Double rating) {
		this.rating = rating;
	}

	public Date getPublishdate() {
		return this.publishdate;
	}

	public void setPublishdate(Date publishdate) {
		this.publishdate = publishdate;
	}

	public Set getMessageRequests() {
		return this.messageRequests;
	}

	public void setMessageRequests(Set messageRequests) {
		this.messageRequests = messageRequests;
	}

	public Set getVoteRequests() {
		return this.voteRequests;
	}

	public void setVoteRequests(Set voteRequests) {
		this.voteRequests = voteRequests;
	}

}
