package model.persistance;

// Generated 29 juin 2010 01:06:24 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * ResponseMessageGroup generated by hbm2java
 */
public class ResponseMessageGroup implements java.io.Serializable {

	private Integer idMessage;
	private MessageGroup messageGroup;
	private Member member;
	private Date publishDate;
	private String body;

	public ResponseMessageGroup() {
	}

	public ResponseMessageGroup(Member member) {
		this.member = member;
	}

	public ResponseMessageGroup(MessageGroup messageGroup, Member member,
			Date publishDate, String body) {
		this.messageGroup = messageGroup;
		this.member = member;
		this.publishDate = publishDate;
		this.body = body;
	}

	public Integer getIdMessage() {
		return this.idMessage;
	}

	public void setIdMessage(Integer idMessage) {
		this.idMessage = idMessage;
	}

	public MessageGroup getMessageGroup() {
		return this.messageGroup;
	}

	public void setMessageGroup(MessageGroup messageGroup) {
		this.messageGroup = messageGroup;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public Date getPublishDate() {
		return this.publishDate;
	}

	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

}
