package model.persistance;

// Generated 29 juin 2010 01:06:24 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Theme generated by hbm2java
 */
public class Theme implements java.io.Serializable {

	private Integer idTheme;
	private String name;
	private String description;
	private Set themeGroups = new HashSet(0);

	public Theme() {
	}

	public Theme(String name, String description, Set themeGroups) {
		this.name = name;
		this.description = description;
		this.themeGroups = themeGroups;
	}

	public Integer getIdTheme() {
		return this.idTheme;
	}

	public void setIdTheme(Integer idTheme) {
		this.idTheme = idTheme;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getThemeGroups() {
		return this.themeGroups;
	}

	public void setThemeGroups(Set themeGroups) {
		this.themeGroups = themeGroups;
	}

}
