package model.persistance;

// Generated 29 juin 2010 01:06:24 by Hibernate Tools 3.2.4.GA

/**
 * VoteBook generated by hbm2java
 */
public class VoteBook implements java.io.Serializable {

	private Integer idVoteBook;
	private Book book;
	private String ip;
	private Double rating;
	private Integer idMember;

	public VoteBook() {
	}

	public VoteBook(Book book) {
		this.book = book;
	}

	public VoteBook(Book book, String ip, Double rating, Integer idMember) {
		this.book = book;
		this.ip = ip;
		this.rating = rating;
		this.idMember = idMember;
	}

	public Integer getIdVoteBook() {
		return this.idVoteBook;
	}

	public void setIdVoteBook(Integer idVoteBook) {
		this.idVoteBook = idVoteBook;
	}

	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public Double getRating() {
		return this.rating;
	}

	public void setRating(Double rating) {
		this.rating = rating;
	}

	public Integer getIdMember() {
		return this.idMember;
	}

	public void setIdMember(Integer idMember) {
		this.idMember = idMember;
	}

}
