package modelcron.persistance;

// Generated Sep 14, 2010 7:01:22 PM by Hibernate Tools 3.2.4.GA

/**
 * BookBk generated by hbm2java
 */
public class BookBk implements java.io.Serializable {

	private Integer idBook;
	private MemberBk memberBk;
	private String linkBook;
	private String keyBook;
	private String linkImage;
	private String linkImageBig;
	private String keyImage;
	private String keyImageBig;
	private String title;
	private Integer idRef;
	private Boolean okL;
	private Boolean okB;
	private Boolean okImg;

	public BookBk() {
	}

	public BookBk(MemberBk memberBk) {
		this.memberBk = memberBk;
	}

	public BookBk(MemberBk memberBk, String linkBook, String keyBook,
			String linkImage, String linkImageBig, String keyImage,
			String keyImageBig, String title, Integer idRef, Boolean okL,
			Boolean okB, Boolean okImg) {
		this.memberBk = memberBk;
		this.linkBook = linkBook;
		this.keyBook = keyBook;
		this.linkImage = linkImage;
		this.linkImageBig = linkImageBig;
		this.keyImage = keyImage;
		this.keyImageBig = keyImageBig;
		this.title = title;
		this.idRef = idRef;
		this.okL = okL;
		this.okB = okB;
		this.okImg = okImg;
	}

	public Integer getIdBook() {
		return this.idBook;
	}

	public void setIdBook(Integer idBook) {
		this.idBook = idBook;
	}

	public MemberBk getMemberBk() {
		return this.memberBk;
	}

	public void setMemberBk(MemberBk memberBk) {
		this.memberBk = memberBk;
	}

	public String getLinkBook() {
		return this.linkBook;
	}

	public void setLinkBook(String linkBook) {
		this.linkBook = linkBook;
	}

	public String getKeyBook() {
		return this.keyBook;
	}

	public void setKeyBook(String keyBook) {
		this.keyBook = keyBook;
	}

	public String getLinkImage() {
		return this.linkImage;
	}

	public void setLinkImage(String linkImage) {
		this.linkImage = linkImage;
	}

	public String getLinkImageBig() {
		return this.linkImageBig;
	}

	public void setLinkImageBig(String linkImageBig) {
		this.linkImageBig = linkImageBig;
	}

	public String getKeyImage() {
		return this.keyImage;
	}

	public void setKeyImage(String keyImage) {
		this.keyImage = keyImage;
	}

	public String getKeyImageBig() {
		return this.keyImageBig;
	}

	public void setKeyImageBig(String keyImageBig) {
		this.keyImageBig = keyImageBig;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Integer getIdRef() {
		return this.idRef;
	}

	public void setIdRef(Integer idRef) {
		this.idRef = idRef;
	}

	public Boolean getOkL() {
		return this.okL;
	}

	public void setOkL(Boolean okL) {
		this.okL = okL;
	}

	public Boolean getOkB() {
		return this.okB;
	}

	public void setOkB(Boolean okB) {
		this.okB = okB;
	}

	public Boolean getOkImg() {
		return this.okImg;
	}

	public void setOkImg(Boolean okImg) {
		this.okImg = okImg;
	}

}
