package modelcron.persistance;

// Generated Sep 14, 2010 7:01:22 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * MemberBk generated by hbm2java
 */
public class MemberBk implements java.io.Serializable {

	private Integer idMember;
	private String login;
	private String avatarUrl;
	private String avatarUrlBig;
	private String keyAvatar;
	private String keyAvatarbig;
	private Boolean okL;
	private Boolean okB;
	private Set bookBks = new HashSet(0);

	public MemberBk() {
	}

	public MemberBk(String login, String avatarUrl, String avatarUrlBig,
			String keyAvatar, String keyAvatarbig, Boolean okL, Boolean okB,
			Set bookBks) {
		this.login = login;
		this.avatarUrl = avatarUrl;
		this.avatarUrlBig = avatarUrlBig;
		this.keyAvatar = keyAvatar;
		this.keyAvatarbig = keyAvatarbig;
		this.okL = okL;
		this.okB = okB;
		this.bookBks = bookBks;
	}

	public Integer getIdMember() {
		return this.idMember;
	}

	public void setIdMember(Integer idMember) {
		this.idMember = idMember;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getAvatarUrl() {
		return this.avatarUrl;
	}

	public void setAvatarUrl(String avatarUrl) {
		this.avatarUrl = avatarUrl;
	}

	public String getAvatarUrlBig() {
		return this.avatarUrlBig;
	}

	public void setAvatarUrlBig(String avatarUrlBig) {
		this.avatarUrlBig = avatarUrlBig;
	}

	public String getKeyAvatar() {
		return this.keyAvatar;
	}

	public void setKeyAvatar(String keyAvatar) {
		this.keyAvatar = keyAvatar;
	}

	public String getKeyAvatarbig() {
		return this.keyAvatarbig;
	}

	public void setKeyAvatarbig(String keyAvatarbig) {
		this.keyAvatarbig = keyAvatarbig;
	}

	public Boolean getOkL() {
		return this.okL;
	}

	public void setOkL(Boolean okL) {
		this.okL = okL;
	}

	public Boolean getOkB() {
		return this.okB;
	}

	public void setOkB(Boolean okB) {
		this.okB = okB;
	}

	public Set getBookBks() {
		return this.bookBks;
	}

	public void setBookBks(Set bookBks) {
		this.bookBks = bookBks;
	}

}
